# Generated by Django 3.0.4 on 2020-06-30 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=20, verbose_name='原物料名稱')),
            ],
            options={
                'verbose_name': '食品原物料',
                'verbose_name_plural': '食品原物料',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20, verbose_name='品項名稱')),
                ('item_price', models.CharField(max_length=10, verbose_name='品項價格')),
                ('time', models.CharField(max_length=10, verbose_name='製作時間')),
                ('sales', models.CharField(max_length=10, verbose_name='售出量')),
            ],
            options={
                'verbose_name': '菜單品項',
                'verbose_name_plural': '菜單品項',
            },
        ),
        migrations.CreateModel(
            name='Have',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10, verbose_name='菜單各原物料價格')),
                ('proportion', models.CharField(max_length=10, verbose_name='比例')),
                ('ingredient', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.Ingredient', verbose_name='食品原物料')),
                ('item', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.Item', verbose_name='菜單品項')),
            ],
            options={
                'verbose_name': '菜單原物料關聯',
                'verbose_name_plural': '菜單原物料關聯',
            },
        ),
    ]
