# Generated by Django 3.0.4 on 2020-07-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miscellaneous_name', models.CharField(max_length=20, verbose_name='人事雜項名稱')),
                ('miscellaneous_price', models.CharField(max_length=10, verbose_name='人事雜項花費')),
                ('service', models.CharField(max_length=10, verbose_name='服務作業比例')),
                ('cooking', models.CharField(max_length=10, verbose_name='料理作業比例')),
                ('sorting', models.CharField(max_length=10, verbose_name='整理管理比例')),
            ],
            options={
                'verbose_name': '人事雜項',
                'verbose_name_plural': '人事雜項',
            },
        ),
        migrations.RemoveField(
            model_name='have',
            name='price',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='原物料價格'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='品項價格'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sales',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='售出量'),
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='製作時間'),
        ),
    ]
