# Generated by Django 3.0.4 on 2020-08-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20200731_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='item',
            field=models.ManyToManyField(through='accounting.Have', to='accounting.Item'),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='cooking',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='料理作業比例'),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='miscellaneous_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='人事雜項花費'),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='service',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='服務作業比例'),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='sorting',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='整理管理比例'),
        ),
    ]
