# Generated by Django 3.0.4 on 2020-08-07 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20200806_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='item',
        ),
        migrations.AlterField(
            model_name='have',
            name='ingredient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounting.Ingredient', verbose_name='食品原物料'),
        ),
        migrations.AlterField(
            model_name='have',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounting.Item', verbose_name='菜單品項'),
        ),
        migrations.AlterField(
            model_name='have',
            name='proportion',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='比例'),
        ),
    ]
