# Generated by Django 3.0.4 on 2020-08-18 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20200808_0348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='have',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterModelOptions(
            name='miscellaneous',
            options={},
        ),
        migrations.AlterField(
            model_name='have',
            name='ingredient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounting.Ingredient'),
        ),
        migrations.AlterField(
            model_name='have',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounting.Item'),
        ),
        migrations.AlterField(
            model_name='have',
            name='proportion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='cooking',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='miscellaneous_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='miscellaneous_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='service',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='sorting',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
