# Generated by Django 3.0.4 on 2020-08-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20200818_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='sales',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.FloatField(default=0),
        ),
    ]
