# Generated by Django 3.0.4 on 2020-08-26 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20200819_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='have',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Ingredient'),
        ),
        migrations.AlterField(
            model_name='have',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Item'),
        ),
        migrations.AlterField(
            model_name='have',
            name='proportion',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='cooking',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='miscellaneous_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='miscellaneous_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='service',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='sorting',
            field=models.FloatField(default=0),
        ),
    ]
