# Generated by Django 3.0.4 on 2020-09-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20200826_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneous',
            name='miscellaneous_time',
            field=models.CharField(default='2020-09', max_length=7),
        ),
    ]
