# Generated by Django 3.0.4 on 2020-09-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_miscellaneous_miscellaneous_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_time',
            field=models.CharField(default='2020-09', max_length=7),
        ),
        migrations.AddField(
            model_name='item',
            name='item_time',
            field=models.CharField(default='2020-09', max_length=7),
        ),
    ]
