# Generated by Django 3.0.4 on 2020-09-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20200903_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_time',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_time',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='miscellaneous_time',
            field=models.CharField(max_length=7),
        ),
    ]
