# Generated by Django 3.0.4 on 2020-10-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_name', models.CharField(max_length=30)),
                ('inventory_date', models.CharField(default='2020-10-08', max_length=10)),
                ('inventory_quantity', models.FloatField(default=0)),
                ('inventory_unitPrice', models.FloatField(default=0)),
            ],
        ),
    ]
