# Generated by Django 3.0.4 on 2020-10-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_date',
            field=models.CharField(default='2020-10-10', max_length=10),
        ),
    ]
