# Generated by Django 3.0.4 on 2020-09-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200907_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_date',
            field=models.CharField(default='2020-09-08', max_length=10),
        ),
    ]
