# Generated by Django 3.0.4 on 2020-10-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20201010_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_date',
            field=models.CharField(default='2020-10-14', max_length=10),
        ),
    ]
