# Generated by Django 3.0.4 on 2020-12-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20201130_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_date',
            field=models.CharField(default='2020-12-05', max_length=10),
        ),
    ]
