# Generated by Django 3.0.4 on 2020-10-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=30)),
                ('employee_id', models.FloatField(default=0, max_length=10)),
                ('employee_time', models.CharField(default='2020-10-08', max_length=10)),
                ('nine_f', models.FloatField(default=0)),
                ('nine_s', models.FloatField(default=0)),
                ('ten_f', models.FloatField(default=0)),
                ('ten_s', models.FloatField(default=0)),
                ('eleven_f', models.FloatField(default=0)),
                ('eleven_s', models.FloatField(default=0)),
                ('twelve_f', models.FloatField(default=0)),
                ('twelve_s', models.FloatField(default=0)),
                ('thirteen_f', models.FloatField(default=0)),
                ('thirteen_s', models.FloatField(default=0)),
                ('fourteen_f', models.FloatField(default=0)),
                ('fourteen_s', models.FloatField(default=0)),
                ('fifteen_f', models.FloatField(default=0)),
                ('fifteen_s', models.FloatField(default=0)),
                ('sixteen_f', models.FloatField(default=0)),
                ('sixteen_s', models.FloatField(default=0)),
                ('seventeen_f', models.FloatField(default=0)),
                ('seventeen_s', models.FloatField(default=0)),
                ('eighteen_f', models.FloatField(default=0)),
                ('eighteen_s', models.FloatField(default=0)),
                ('nineteen_f', models.FloatField(default=0)),
                ('nineteen_s', models.FloatField(default=0)),
                ('twenty_f', models.FloatField(default=0)),
                ('twenty_s', models.FloatField(default=0)),
                ('twentyOne_f', models.FloatField(default=0)),
                ('twentyOne_s', models.FloatField(default=0)),
                ('twentyTwo_f', models.FloatField(default=0)),
                ('twentyTwo_s', models.FloatField(default=0)),
                ('twentyThree_f', models.FloatField(default=0)),
                ('twentyThree_s', models.FloatField(default=0)),
                ('twentyFour_f', models.FloatField(default=0)),
                ('twentyFour_s', models.FloatField(default=0)),
            ],
        ),
    ]
